name: Deploy PM2

on:
  push:
    branches:
      - main

jobs:
  update-pm2:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 stop all
            pm2 start /var/www/restart_pm2.sh
